---
title: "Tidy Tuesday 2023-04-15"
author: "Jesse Jones"
date: "2023-04-14"
output: 
  prettydoc::html_pretty:
    theme: tactile
    highlight: github
---

## Data Sources & Credits

### **Data Source**: [US Egg Production Data 2007-2021](https://osf.io/z2gxn/)

### **TidyTuesday Data 2023-04-11**: [US Egg Production](https://github.com/rfordatascience/tidytuesday/blob/master/data/2023/2023-04-11/readme.md)

### **Article Link**: [The Humane League Labs US Egg Production Dataset](https://thehumaneleague.org/article/E008R01-us-egg-production-data)

##### Article Author: Samara Mendez

##### Article Date: Aug 12, 2019

##### Article Revision: Revised March 8, 2021

### [Official Tidy Tuesday Github Repo](https://github.com/rfordatascience/tidytuesday)

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Libraries

```{r Libraries}
library(tidyverse)
library(here)
```

## Get the Data

```{r data, echo=FALSE}
eggproduction  <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/egg-production.csv')
cagefreepercentages <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-04-11/cage-free-percentages.csv') #read in our csvs from tidytuesday repository
```

Data Wrangling

```{r Data Wrangling, warning=FALSE, echo=TRUE}
production_filtered <- eggproduction %>% 
  filter(prod_type=="table eggs", prod_process=="all") %>% #filter by only table eggs within the prod_type column and only "all" within the prod_process column
  select(observed_month, n_eggs) #select data from only these columns

eggs_data <- full_join(production_filtered, cagefreepercentages) %>% #join all the data available from these dataframes, combining the "observed_month" data
  select(observed_month, percent_eggs, n_eggs) %>% #select only these columns
  drop_na() %>% #remove rows with NAs
  mutate(number_cagefree=.01*percent_eggs*n_eggs) #create a column of total cagefree eggs for each month
```

## Make a Plot

```{r ggplot, warning=FALSE, echo=TRUE}
ggplot(data=eggs_data,aes(x=observed_month, y=percent_eggs, color=number_cagefree))+ #create a plot with my months on my x axis, percent of cagefree eggs on my y axis, and color representing the total number of cagefree eggs
  geom_point(size=3)+ #create a scatter plot
  scale_color_viridis_c()+ #add color-blind friendly colors for continuous scale? (I think)
  geom_smooth()+ #add the geom_smooth() line to my plot
  labs(title="Percentage of US-produced, Cagefree Eggs (Compared to Total US-produced Eggs) 
       Appears To Have Increased Over Time Between August, 2016 and February, 2021", #this is my plot title
       x="Time - data points at each month during the time course", #this is my x-axis title
       y="Percentage of Cagefree Table Eggs", #this is my y-axis title
       color="Number of US Cagefree Eggs") + #Title of color legend
 theme_light(base_size=8.3)+ #use the light theme and modify the ratio of plot size to text size
  theme(plot.title=element_text(hjust=1.5)) #adjust the horizontal position of the title
#ggsave(here( "Tidy_Tuesday_2023_04_14", "Output", "plot.png")) #save my plot image to this pathway and file name
```
